---
title: "Course Project: Developing Data Products"
author: "Jane Nyandele"
date: "2023-06-11"
output: ioslides_presentation
---

## Introduction

This presentation is part of the project "Developing Data Products" offered by Coursera

This markdown presentation is generated by Rstudio

The presentation discusses a Shiny application, as well as the corresponding Shiny app source code


## Overview

- The source code for this app contains two files: server.R and ui.R
- server.R includes the backend of the Shiny app web application
- ui.R includes the user interface elements
- The application is hosted in the Rstudio's Shiny server

The aim of this application is to provide a friendly interface for exploring three (3) datasets namely;
cars, iris and airquality. The application provides options for choosing a dataset of interest and 
viewing summary information as well as the actual observations. 

## How the App works?
Main panel - Access the dataset summary - See the dataset table with some observations

Side panel - Select the dataset of interest - Change the number of desired observations


## Try experiencing the App

Use the Shiny app at https://nyandele.shinyapps.io/Jane_Project/

Get the app source code at 
